# Generated by Django 5.1.2 on 2024-10-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('Username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Email', models.CharField(max_length=20, unique=True)),
                ('Password', models.CharField(blank=True, max_length=12)),
            ],
        ),
    ]
