# Generated by Django 5.1.2 on 2024-10-21 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Loginify', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
