# Generated by Django 5.1.2 on 2024-10-21 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Loginify', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdetails',
            options={'verbose_name': 'User Detail'},
        ),
    ]
